
server:
  servlet:
    context-path: /
    session:
      timeout: 30s
  port: 9966


spring:
#  main:
#    web-application-type: reactive
  application:
    name: bao-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 路由配置
    gateway:
      routes:
#        - id: rrr
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
        - id: product_route
          uri: lb://bao-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/bao-product/$\{segment}

        - id: user_route
          uri: lb://bao-auth
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/bao-auth/$\{segment}




logging:
  level:
    org.springframework.cloud.gateway: DEBUG
