
server:
  servlet:
    context-path: /
    session:
      timeout: 30s
  port: 9602


spring:
  application:
    name: bao-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 路由配置
    gateway:
      routes:
        - id: user_route
          uri: lb://auth
          predicates:
            - Path=/api/**

        - id: rrr
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
